const Mailgen = require('mailgen');
const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    auth: {
        user: process.env.EMAIL,
        pass: process.env.PASSWORD
    }
});

const registerMail = async (req, res) => {
    const { username, userEmail, text, subject } = req.body;

    // Body of the email
    const email = {
        body: {
            name: username,
            intro: text || 'Welcome to Daily Tuition! We\'re very excited to have you on board.',
            outro: 'Need help, or have questions? Just reply to this email, we\'d love to help.',
        }
    };

let mailGenerator = new Mailgen({
    theme: "default",
    product: {
        name: "Mailgen",
        link: "https://mailgen.js",
    }
});

    const emailBody = mailGenerator.generate(email);

    let message = {
        from: process.env.EMAIL,
        to: userEmail,
        subject: subject || "Signup Successful",
        html: emailBody,
    };

    try {
        await transporter.sendMail(message);
        return res.status(200).send({ msg: "You should receive an email from us." });
    } catch (error) {
        console.error('Error sending email:', error);
        return res.status(500).send({ error: 'Failed to send email.' });
    }
};

module.exports = { registerMail };


// const Mailgen = require('mailgen');
// const nodemailer = require('nodemailer');
// require('dotenv').config();

// // Create transporter using Ethereal SMTP server
// const transporter = nodemailer.createTransport({
//     host: 'smtp.ethereal.email',
//     port: 587,
//     secure: false, // use TLS
//     auth: {
//         user: process.env.EMAIL, // from .env
//         pass: process.env.PASSWORD // from .env
//     }
// });

// // Function to send registration email
// const registerMail = async (req, res) => {
//     const { username, userEmail, text, subject } = req.body;

//     // Make sure we have all required fields
//     if (!userEmail || !username) {
//         return res.status(400).send({ error: "Missing required fields" });
//     }

//     // Body of the email
//     const email = {
//         body: {
//             name: username,
//             intro: text || 'Welcome to Daily Tuition! We\'re very excited to have you on board.',
//             outro: 'Need help, or have questions? Just reply to this email, we\'d love to help.',
//         }
//     };

//     // Initialize Mailgen
//     let mailGenerator = new Mailgen({
//         theme: "default",
//         product: {
//             name: "Mailgen",
//             link: "https://mailgen.js",
//         }
//     });

//     // Generate email body
//     const emailBody = mailGenerator.generate(email);

//     // Set up the email message
//     let message = {
//         from: process.env.EMAIL, // From email (set in .env)
//         to: userEmail, // To email
//         subject: subject || "Signup Successful", // Subject
//         html: emailBody, // HTML body generated by Mailgen
//     };

//     try {
//         // Attempt to send the email
//         await transporter.sendMail(message);
//         return res.status(200).send({ msg: "You should receive an email from us." });
//     } catch (error) {
//         // Log the error with more details for debugging
//         console.error('Error sending email:', error);
//         console.error('Error details:', error.response ? error.response.body : error);
//         return res.status(500).send({ error: 'Failed to send email.', details: error.message });
//     }
// };

// module.exports = { registerMail };
